### ISSUE TITLE
Charm errors when relating to Kubeflow

### ISSUE THREAD

**Issue by SpontaneousDuck** [canonical/mlflow-operator#9] opened 2022-01-28 23:10 UTC
I am deploying this charm alongside the full Kubeflow 1.4 charm and am running in to errors after relating mlflow-server to admission-webhook. It seems the charm will not start until this relation is created after creating, the mlflow-server charm fails with this error:
```
application-mlflow-server: 23:05:23 ERROR unit.mlflow-server/2.juju-log pod-defaults:31: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 282, in <module>
    main(Operator)
  File "/var/lib/juju/agents/unit-mlflow-server-2/charm/venv/ops/main.py", line 406, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mlflow-server-2/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mlflow-server-2/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mlflow-server-2/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mlflow-server-2/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 57, in _on_pod_defaults_relation_changed
    endpoint = f"http://{obj_storage['service']}:{obj_storage['port']}"
KeyError: 'service'
```

And the admission-webhook charm fails with this error:
```
Traceback (most recent call last):
  File "./src/charm.py", line 317, in <module>
    main(AdmissionWebhookCharm)
  File "/var/lib/juju/agents/unit-admission-webhook-2/charm/venv/ops/main.py", line 401, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-admission-webhook-2/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-admission-webhook-2/charm/venv/ops/framework.py", line 234, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-admission-webhook-2/charm/venv/ops/framework.py", line 678, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-admission-webhook-2/charm/venv/ops/framework.py", line 723, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 157, in set_pod_spec
    pod_defaults = {
  File "./src/charm.py", line 158, in <dictcomp>
    key.name: dict(value)["pod-defaults"]
KeyError: 'pod-defaults'
```

I have tried with both the stable and edge versions of the mlflow-server charm and see the same issue both times. After removing the relation, the admission-webhook charm never comes back as well and needs to be removed and re-deployed.

**Comment by grobbie** [comment] 2022-01-31 07:07
I would like to add that once this happens, it totally breaks the JuJu model - the mlflow-server charm cannot be removed from the model and the admission-webhook charm is also permanently chewed.

**Comment by DnPlas** [comment] 2022-02-04 19:24
Hi @SpontaneousDuck, thanks for reporting this. 
Please note `admission-webhook` is not a required relation for `mlflow` (you can see all required relations in the [bundle definition](https://github.com/canonical/mlflow-operator/blob/master/bundle.yaml#L19)), and the traceback you posted is due to a relation interface not being recognized by either of the charms. What you are probably experiencing is an error in the unit that is caused by `admission-webhook` not being `active` before you deploy `mlflow`. My suggestion is you deploy Kubeflow and wait until it is all active before deploying any other charm. Could you please try that and report your findings? Please also include the output of `juju status mlflow-server` and `juju status admission-webhook` if you run into the issue again.

Here are my steps to reproduce this issue: 
1. Deployed Kubeflow v1.4 (following [this](https://charmed-kubeflow.io/docs/install) guide) on a Microk8s 1.21 cluster, waited for everything to be active
2. Deployed `mlflow` with `juju deploy mlflow`

**Comment by grobbie** [comment] 2022-02-04 20:23
The [readme](https://github.com/canonical/mlflow-operator#:~:text=hub%2Dpassword%3E%0Abash-,integration_test_microk8s,-Set%20the%20docker) suggests using [this test script which relates the two](https://github.com/canonical/mlflow-operator/blob/4bdda5d0a545821109c380b8d460c69c6d5de9be/integration_test_microk8s#L71) which is a bit confusing. We should improve the documentation and revisit that test script.

**Comment by DomFleischmann** [comment] 2022-02-08 13:35
We got a separate [issue](https://github.com/canonical/mlflow-operator/issues/10) for updating the MLFlow documentation and someone will work on it in the next weeks. I will close this issue therefore.

**Closed by DomFleischmann** 2022-02-08 13:35 UTC
Labels: invalid
