### ISSUE TITLE
CheckFailedError sets WaitingStatus class with NoVersionsListed instead of string

### ISSUE THREAD

**Issue by phvalguima** [canonical/mlflow-operator#30] opened 2022-03-11 14:10 UTC
In a situation where istio-pilot fails to publish the ```_supported_version``` information in time to mlflow-server, mlflow charm will throw an error: NoVersionsListed and try to create a WaitingStatus of it.

However, due to:

```
    def _get_interfaces(self):
        try:
            interfaces = get_interfaces(self)
        except NoVersionsListed as err:
            raise CheckFailedError(err, WaitingStatus)

....

class CheckFailedError(Exception):
    """Raise this exception if one of the checks in main fails."""

    def __init__(self, msg, status_type=None):
        super().__init__()

        self.msg = str(msg)
        self.status_type = status_type
        self.status = status_type(msg) ## <<<------ missing a str conversion
```

That ends up causing the following failure when updating the status: https://pastebin.canonical.com/p/PRYBkxJcxk/

**Comment by DnPlas** [comment] 2022-05-05 21:19
Hi @phvalguima , thanks for reporting this.
That piece of code in your description was modified recently by [this](https://github.com/canonical/mlflow-operator/commit/db1417c1faf174f670322e10422462d006c6f638#diff-9b591181fb63b6dd090d92c6c9cd8f13b88d846b6e470a340ac19d0c0b28240aR285) commit, which added, among other things, the missing string casting. I tried reproducing the issue using the latest version of this charm and seems like the issue is not present anymore. 
I'm closing this issue, but feel free to re-open it if you run into the error again.

**Closed by DnPlas** 2022-05-05 21:19 UTC
Labels: bug, good first issue
